config/routes.rb
Rails.application.routes.draw do

  
  get '/auth/:provider/callback', to: 'sessions#create'

  root 'pages#index'
  resources :flags do
    resources :flag_layers, :shallow => true
  end

end

app/models/flag.rb
class Flag < ActiveRecord::Base
  has_many :flag_layers
  has_one :base_layer, :class_name => FlagLayer

  accepts_nested_attributes_for :flag_layers

  validates_associated :flag_layers
  validates :base_layer, :presence => true

  validate :exactly_one_base_layer

  before_create :assign_secret


  private

  def assign_secret
    secret = "#{RandomWord.adjs.next}-#{RandomWord.nouns.next}"
    while Flag.where(:secret => secret).count > 0
      secret = "#{RandomWord.adjs.next}-#{RandomWord.nouns.next}"
    end
    self.secret = secret
  end

  def exactly_one_base_layer
    if self.base_layer.is_base_layer? == false
      errors.add(:base_layer, "must be set.")
    end
    if self.flag_layers.where(:is_base_layer => true).count > 1 
      errors.add(:base_layer, "must be present exactly once.")
    end
  end

end

app/models/flag_layer.rb
class FlagLayer < ActiveRecord::Base
  belongs_to :flag
  before_create :populate_sortorder
  validates :width, :height, :numericality => { :only_integer => true }

  scope :template, -> { where(:is_base_layer => false, :is_template => true) }
  scope :base, -> { where(:is_base_layer => true) }

  private

  def populate_sortorder
    if self.flag && self.sortorder.nil?
      self.sortorder = self.flag.flag_layers.count
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_auth_hash(auth_hash)
    user = self.where(:provider => auth_hash['provider'],
                      :uid      => auth_hash['uid'].to_s).first_or_create
    user.nick = auth_hash['info']['name']
    user.save
    return user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue Exception 
      nil
    end
  end

end

app/controllers/flag_layers_controller.rb
class FlagLayersController < ApplicationController


  def new
    @flag = Flag.find(params[:flag_id])
    @templates = FlagLayer.template.all
    @flag_layer = FlagLayer.new(:flag => @flag)
  end

  def create
    @flag = Flag.find(params[:flag_id])
    @flag_layer = FlagLayer.new(flag_layer_params)
  end

  private

  def flag_layer_params
    params.require(:flag_layer).permit(:color1)
  end
end

app/controllers/flags_controller.rb
class FlagsController < ApplicationController

  def flag_and_layers
    if params[:id]
      @flag = Flag.find(params[:id])
      @base_layer = @flag.base_layer
    else
      @flag = Flag.new
      layer = FlagLayer.new(:is_base_layer => true)
      @flag.base_layer = layer
    end
  end

  def show
    flag_and_layers
    respond_to do |format| 
      format.svg
      format.html
    end
  end

  def new
    flag_and_layers
  end

  def edit
    flag_and_layers
  end

  def update
    flag_and_layers
    @flag.update_attributes(flag_params)
    respond_to do |format| 
      format.html { 
        redirect_to :action => :edit, :params => { :secret => @flag.secret } 
      }
    end
  end

  private

  def flag_params
    params.require(:flag).permit(:flag_layers_attributes => 
                                 [ :id, :sortorder,
                                   :color1, :color2, :color3, 
                                   :color4, :color5, :color6,
                                   :stroke1, :stroke2, :stroke3, 
                                   :stroke4, :stroke5, :stroke6 
                                 ]
                                )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # Otherwise Rails will helpfully clear the whole env for us and drop the
  # omniauth.auth key.
  protect_from_forgery :except => :create

  def create
    user = User.from_auth_hash(auth_hash)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flag_layers_helper.rb
module FlagLayersHelper

  def color_picker_field(layer_form, color, property = "fill")
    if property == "stroke"
      layer_form.text_field(color.to_sym,  :size => 7, :class => 'colorpicker',
                            :data => { :altfield => "#flag_layer_#{layer_form.object.id} .#{color}",
                                       :altproperties => 'stroke'} )
    else
      layer_form.text_field(color.to_sym,  :size => 7, :class => 'colorpicker',
                            :data => { :altfield => "#flag_layer_#{layer_form.object.id} .#{color}"} )
    end
  end
end

app/helpers/flags_helper.rb
module FlagsHelper

  def random_hexcolor
    [rand(0...255), rand(0...255), rand(0...255)].map{|x| '%02x'%x}.join
  end
end

app/views/flag_layers/_color_pickers.html.erb
Fills: <% (1..layer_form.object.max_colors).each do |i| %>
  <%= color_picker_field(layer_form, "color#{i}") %>
<% end %>
<br/>
Strokes: <% (1..layer_form.object.max_strokes).each do |i| %>
  <%= color_picker_field(layer_form, "stroke#{i}", 'stroke') %>
<% end %>

app/views/flag_layers/_editor.html.erb
<div class="group ui-state-default <%= 'sortable' unless layer_form.object.is_base_layer? %>" data-targetid="<%= "#flag_layer_#{layer_form.object.id}" %>">


  <h3 class="ui-accordion-header">Template: <%= layer_form.object.template_name %> <%= '(base layer)' if layer_form.object.is_base_layer? %></h3>
  <div class="ui-accordion-content">
    <%= render :partial => 'flag_layers/color_pickers', :locals => {:layer_form => layer_form} %>
    <% unless layer_form.object.is_base_layer? %>
    <%= layer_form.hidden_field :sortorder, :data => { :fieldname => 'sortorder' } %>
    <% end %>
  </div>
</div>

app/views/flag_layers/new.html.erb
<h1>New flag layer</h1>

<p>Foo.</p>

<%= form_for [@flag, @flag_layer] do |f| %>
  <%= f.select(:template_name, options_from_collection_for_select(@templates, :template_name, :id)) %>
<% end %>

app/views/flags/_form.html.erb
<h2>Layers</h2>

<%= @flag.flag_layers.order("sortorder DESC").collect(&:id) %>
<%= @flag.flag_layers.order("sortorder DESC").collect(&:sortorder) %>

<%= form_for @flag do |f| %>
  <div id="flag_editor" class="ui-accordion">
    <%= f.fields_for :flag_layers, @flag.flag_layers.order("sortorder DESC") do |layer_form| %>
      <%= render :partial => 'flag_layers/editor', :locals => { :layer_form => layer_form } %>
    <% end %>
  </div>
  <%= hidden_field_tag :secret, params[:secret] %>
  <%= f.submit %>
<% end %>

app/views/flags/edit.html.erb
<h2>Flag <%= @flag.id %></h2>

<div id="flag">
  <%= render :file => 'flags/show.svg.erb' %>
</div>

<%= render 'form' %>

app/views/flags/layers/_cross_of_burgundy.svg.erb
<path
fill="<%= layer.color1 %>"
class="color1"
id="path4873"
d="m 586.2,335.76 32.04,-9.6 52.68,31.92 -33.36,8.64 49.44,29.76 33,-8.88 52.08,31.56 -33.72,8.16 49.56,29.88 33.96,-8.28 52.2,31.68 -32.04,9.24 57.96,34.8 0,75.36 -41.28,0 -71.04,-43.08 9.71999,34.2 -56.03999,-33.36 -9.24,-34.2 -48.72001,-29.16 7.56,33.12 -51.35999,-30.6 -9,-34.2 -49.32,-29.52 8.27999,33.72 L 536.28,435 527.64,401.04 449.88,354.48 372,401.04 363.36,435 l -53.28,31.92 8.28,-33.72 -49.32,29.52 -9,34.2 -51.36,30.6 7.56,-33.12 -48.72001,29.16 -9.23999,34.2 -56.04,33.36 9.72,-34.2 L 41.279999,600 0,600 0,524.64 57.84,489.84 25.8,480.6 77.999999,448.92 111.96,457.2 161.52,427.32 127.8,419.16 180,387.6 l 33,8.88 49.44,-29.76 -33.36,-8.64 52.68,-31.92 32.04,9.6 52.32,-31.44 -41.88,-25.08 -32.04001,9.6 -52.79999,-31.8 33.24,-8.76 -49.56,-29.64 -33,8.88 -52.2,-31.56 33.72,-8.28 L 122.04,157.92 88.2,166.44 35.88,134.88 67.92,125.64 0,81.12 0,0 l 28.32,0 94.8,57 -9.6,-34.2 55.92,33.48 9.24,34.2 48.6,29.28 -7.44,-33.12 51.24,30.6 8.88,34.2 49.32,29.64 -8.28,-33.72 53.16,32.04 8.64,33.96 67.19999,40.44 L 517.2,213.36 525.83999,179.4 579,147.36 l -8.28,33.72 49.32,-29.64 8.88,-34.2 51.24,-30.6 -7.44,33.12 48.59999,-29.28 9.24001,-34.2 55.92,-33.48 -9.6,34.2 94.8,-57 28.32,0 0,81.12 -67.92001,44.4 32.04001,9.24 -52.32001,31.56 -33.95999,-8.28 -49.56,29.76 33.71999,8.28 -52.19999,31.56 -33.00001,-8.88 -49.56,29.64 33.24001,8.76 -52.8,31.8 -32.04001,-9.6 -41.87999,25.08 52.44,31.32 z" />

app/views/flags/layers/_tricolour_vertical.svg.erb
<rect width="900" height="600" fill="<%= layer.color3 %>" class="color3"/>
<rect width="600" height="600" fill="<%= layer.color2 %>" class="color2"/>
<rect width="300" height="600" fill="<%= layer.color1 %>" class="color1"/>

app/views/flags/new.html.erb
<h1>New flag</h1>

<p>Choose base layer:</p>

<%= form_for @flag do |f| %>
  <%= f.fields_for :flag_layers do |flag_layers_form| %>
    <%= flag_layers_form.text_field(:template_name) %>
    <%= flag_layers_form.text_field(:width) %>
    <%= flag_layers_form.text_field(:height) %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/flags/show.html.erb
<h2>Flag <%= @flag.id %></h2>

<%= render :file => 'flags/show.svg.erb' %>

<p>
  <%= link_to('Download flag as SVG', flag_path(@flag, :format => 'svg')) %> (Might have to right-click and 'Save as...')
</p>

app/views/flags/show.svg.erb
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="<%= @flag.base_layer.width %>" height="<%= @flag.base_layer.height %>">

<% @flag.flag_layers.order("sortorder ASC").each do |layer| %>
  <g class="layer <%= 'base_layer' if layer.is_base_layer? %>" id="flag_layer_<%= layer.id %>">
  <%= render :partial => "flags/layers/#{layer.template_name}.svg.erb", :locals => { :layer => layer } %>
  </g>
<% end %>

</svg>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flagellant</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">
  <%= javascript_include_tag 'application'  %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <%= link_to("Flagellant", root_path, :class => 'navbar-brand') %>
  </nav>


  <div class="container">
    <% if flash %>
      <div class="messages">
      <% if flash[:error] %>
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
          <%= flash[:error] %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>